#STAGE 1
FROM node:19-alpine as installer
WORKDIR /app
COPY ./package.json ./package.json
RUN ["npm", "install"]

#STAGE 2
FROM node:19-alpine
WORKDIR /app
COPY --from=installer /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start"]