version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: dreamhouse_db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamhouse_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/datadump.sql
    networks:
      - dreamhouse_net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dreamhouse_phpmyadmin
    ports:
      - 8080:80
    links:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - dreamhouse_net
  backend:
    build: ./backend
    container_name: dreamhouse_backend
    command: sh -c '/app/wait-for-it.sh -t 0 db:3306 -- python ./manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dreamhouse_net
  frontend:
    build: ./frontend
    container_name: dreamhouse_frontend
    depends_on:
      - backend
    restart: always    
    ports:
      - "3000:3000"
    networks:
      - dreamhouse_net
volumes:
  dbdata:
networks:
  dreamhouse_net: